### ISSUE TITLE
Example in README not working

### ISSUE THREAD

**Issue by sje30** [henrikkarlstrom/rcristin#1]
Hi,

thanks for providing rcristin.  It looks very useful; we are running a workshop next week introducing R for scholarly comms researchers etc at the Munin conference.  I'd like to showcase your package.  

I don't know my way around cristin, but your package looks like it will be just the ticket.  However, I can't get the example on your project front page (README) to work; it looks like you have changed the interface so that the results are stored in the "results" element of the returend list.  I've managed to get some of the code working by rewriting it a bit, see, e.g.

https://github.com/sje30/munin-R/blob/main/rcristin/rcristin.R

(Incidently if you browse the munin-R you can see what we are planning; one exercise will be to use your rcristin package instead of the rorcid package to mine information about users and their publications).

If you have any freely available code using rcristin that we can refer to that would also be great.

Best wishes, Stephen

cc: @nuest

**Comment by henrikkarlstrom** [comment]
Thanks for the heads up! I have updated the README with an example that works (for me, at least) as of the latest commit:

https://github.com/henrikkarlstrom/rcristin/commit/bb7700d7ae8b7d101c8837a783a8153a7433c456

I have also made some changes to the functionality of the package, including reverting to returning a single dataframe from get_cristin_results() - this time with list columns included. With the improved unnest() and hoist() functions in tidyr::, list columns with NULL values (common with API results) are now much easier to handle, and returning the various components of a nested JSON file as a list of split up data frames is no longer as attractive.

No interesting public code using rcristin yet, but I will put some up.

**Comment by henrikkarlstrom** [comment]
Here is improved documentation for the package:

https://henrikkarlstrom.github.io/rcristin/index.html

And here is an example use case article for the different functions in rcristin:

https://henrikkarlstrom.github.io/rcristin/articles/use_case.html

**Comment by sje30** [comment]
This looks super, thank you!  Will follow by email tonight.
